export const services = [
  { slug:'web-development', name:'Web Design & Development', seoTitle:'Conversion-Focused Web Design', seoDescription:'Conversion-focused web design and development for service businesses. Turn more of the right visitors into calls, bookings, and qualified enquiries.', short:'Turn more of the right visitors into qualified enquiries.', intro:'Your website should do more than prove you exist. We build conversion-focused websites that explain your value, earn trust, and make the next step obvious.', items:['Website strategy & buyer journeys','Conversion-focused copy structure','Custom responsive design','WordPress, Shopify & Astro development','Forms, bookings & integrations','Performance, accessibility & maintenance'], outcome:'A faster, clearer sales journey from first visit to qualified enquiry.', category:'DESIGN / DEVELOPMENT' },
  { slug:'branding-seo', name:'Branding & SEO', seoTitle:'Branding, Local SEO & Search Strategy', seoDescription:'Branding and SEO for service businesses that need to look established, rank for relevant searches, and earn trust before the first conversation.', short:'Look established. Show up when buyers are searching.', intro:'Being good at the work is not enough if people cannot find you or cannot tell why you are different. We align your brand, website, and search presence around one credible story.', items:['Positioning & visual identity','Search intent & competitor research','On-page & technical SEO','Local SEO strategy','Google Business Profile optimisation','Content planning & reporting'], outcome:'A recognisable brand and stronger visibility for searches that can lead to business.', category:'IDENTITY / SEARCH' },
  { slug:'digital-marketing', name:'Digital Marketing', seoTitle:'Digital Marketing & Lead Generation', seoDescription:'Digital marketing for service businesses, connecting paid search, social ads, landing pages, and conversion tracking around qualified lead generation.', short:'Connect every paid click to a believable reason to act.', intro:'Buying traffic is easy. Turning it into profitable work is where the thinking starts. We connect the audience, offer, creative, landing page, and measurement into one campaign journey.', items:['Campaign & offer strategy','Google Ads','Paid social campaigns','Conversion landing pages','Call, form & conversion tracking','Performance review & optimisation'], outcome:'Campaigns measured by useful business signals, not impressive-looking activity.', category:'STRATEGY / CAMPAIGNS' },
  { slug:'email-marketing', name:'Email Marketing', seoTitle:'Email Marketing & Automation', seoDescription:'Email marketing and automation for service businesses. Follow up with leads, answer objections, nurture trust, and stay relevant after the first enquiry.', short:'Stop letting interested leads quietly disappear.', intro:'A lead can be genuinely interested and still get distracted. We build useful follow-up journeys that answer the next question, reduce uncertainty, and give people a natural reason to return.', items:['Follow-up strategy','Campaign copy & design','Welcome & nurture sequences','Lead segmentation','Email platform & automation setup','Campaign measurement'], outcome:'A consistent follow-up system that keeps good opportunities from going cold by default.', category:'EMAIL / RETENTION' },
  { slug:'content-writing', name:'Content & Reputation', seoTitle:'Website Copywriting & SEO Content', seoDescription:'Website copywriting, SEO content, and reputation strategy that turn service-business expertise into clear reasons to trust, choose, and contact you.', short:'Turn what you know into reasons to trust and choose you.', intro:'Vague claims make capable businesses sound interchangeable. We turn your expertise, process, and proof into website copy and useful content that buyers can understand and search engines can interpret.', items:['Website & landing-page copy','Brand voice & messaging','SEO service content','Articles & answer-led content','Reputation analysis','Review response guidance'], outcome:'A credible voice that answers real buying questions and makes your value easier to recognise.', category:'CONTENT / REPUTATION' },
  { slug:'waas', name:'Website as a Service', seoTitle:'Website as a Service for Businesses', seoDescription:'Website as a Service for small and service businesses: website design, development, hosting, maintenance, updates, SEO, and ongoing support in one monthly plan.', short:'Get the website and ongoing support without managing five vendors.', intro:'Most websites slowly become outdated because nobody owns the next update. Website as a Service gives design, development, maintenance, and agreed growth work one accountable home.', items:['Website strategy, design & build','Launch & hosting coordination','Maintenance & security','Content and service updates','Performance monitoring','A defined monthly growth scope'], outcome:'A website that stays current, useful, and supported as the business changes.', category:'WEBSITES / ONGOING CARE' }
];

export const projects = [
  { slug:'vital-tails', name:'Vital Tails', subtitle:'Making veterinary care feel easier to trust.', sector:'VETERINARY & PET CARE', image:'/images/vital-tails.webp', imageAlt:'Veterinary care imagery from the Vital Tails website', tone:'peach', url:'https://vitaltailsvet.com/', description:'Pet owners arrive with questions and, sometimes, worry. The Vital Tails website uses warm imagery, plain-language service information, and clear contact paths to make the first step feel less uncertain.', tags:['Web Design','Development'], mark:'vital tails', line:'A little love. A lot of care.' },
  { slug:'omnifood', name:'Omnifood', subtitle:'Turning a subscription concept into a simple decision.', sector:'FOOD & LIFESTYLE', image:'/images/omnifood.webp', imageAlt:'A selection of fresh meals from the Omnifood website', tone:'orange', url:'https://omnifood-project-umar.netlify.app/', description:'A subscription can feel complicated before it feels convenient. This concept leads with appetite, then explains the offer, process, and plan in the order a potential customer needs them.', tags:['Web Design','Development'], mark:'omnifood', line:'Eat well. Live more.' }
];

export type Project = typeof projects[number];

export const faqs: [string, string][] = [
  ['Who is PressPixel Creations best suited for?','We are best suited to service businesses that do strong work but are being held back by an unclear website, weak search visibility, inconsistent follow-up, or a digital presence that no longer reflects the business.'],
  ['Can you improve my existing website instead of starting again?','Yes. We first identify whether the problem is positioning, copy, structure, design, technology, traffic, or follow-up. If the existing foundation is sound, we can improve it. If rebuilding is the more sensible investment, we will explain why.'],
  ['How much does a website cost?','Custom project pricing depends on the pages, content, integrations, and technical requirements. Our ongoing Website as a Service plans currently start at $999.99 per month. Every engagement begins with a written scope, price, and responsibilities.'],
  ['Is SEO included with web design?','Every website receives sensible search foundations such as crawlable structure, page titles, descriptions, headings, and performance consideration. Ongoing keyword strategy, local SEO, content, link building, and reporting are separate services unless your proposal or plan includes them.'],
  ['What happens after launch?','We can hand over a completed project or continue through maintenance, Website as a Service, SEO, content, email, and campaign support. The proposal makes ownership, access, hosting, updates, and ongoing responsibilities clear before work begins.']
];
