export type ServiceDetail = { headline:string[]; lead:string; question:string; answer:string; chapters:[string,string][]; steps:[string,string][]; faqs:[string,string][]; related:string[] };

export const serviceDetails: Record<string, ServiceDetail> = {
  'web-development': {
    headline:['Stop losing good leads.','Make every visit count.'],
    lead:'When people cannot quickly understand what you do, why they should trust you, and what to do next, they leave. We design that uncertainty out of the journey.',
    question:'Why do capable service businesses still lose leads through their websites?',
    answer:'Usually, the business is not the problem. The website is asking visitors to decode vague language, hunt for proof, compare unclear services, or take a leap before they feel ready. We put the buying questions in the right order and build a clear path from arrival to enquiry.',
    chapters:[
      ['A message buyers understand quickly','The opening screen should tell the right visitor what you help with, who it is for, and why it matters. We replace broad claims with a specific value proposition and a useful next step.'],
      ['Proof where hesitation happens','Testimonials, work examples, process detail, credentials, FAQs, and honest expectations belong near the questions they answer. Trust should build as the visitor moves, not wait at the bottom of the page.'],
      ['Pages built around decisions','Service pages explain the problem, approach, deliverables, fit, and next step. Navigation, internal links, and calls to action help people move without forcing every visitor down the same route.'],
      ['A fast, dependable build','Responsive layouts, accessible controls, clean code, forms, booking tools, analytics, and agreed integrations turn the strategy into a website people can actually use.']
    ],
    steps:[['Find the leak','Review the audience, offer, analytics, current pages, and points where confidence breaks.'],['Build the argument','Shape the sitemap, messaging, proof, and page journeys before polishing screens.'],['Design and develop','Create a distinctive responsive system, build it, and connect the required tools.'],['Test the real journey','Check speed, navigation, forms, tracking, and key actions before a controlled launch.']],
    faqs:[['What makes a website conversion-focused?','It gives the right visitor enough clarity and confidence to take the next sensible step. That means a specific message, relevant proof, low-friction navigation, strong service pages, usable forms, and measurement tied to calls, bookings, or enquiries.'],['Can you redesign my existing website without hurting SEO?','We preserve useful content and important URLs where sensible, map redirects when URLs change, and review titles, metadata, internal links, indexability, and technical performance. No redesign can guarantee rankings, but migration risk can be managed carefully.'],['Which platform will you use?','The platform follows the job. We work with WordPress, Shopify, Astro, and other suitable stacks. Editing needs, integrations, performance goals, budget, and maintenance preferences guide the recommendation.'],['How long does a website project take?','Timing depends on page count, content readiness, feedback, integrations, and platform. Your proposal sets out the phases and target schedule once the scope is understood.']],
    related:['content-writing','branding-seo']
  },
  'branding-seo': {
    headline:['Look established.','Show up when buyers search.'],
    lead:'A forgettable identity makes you easier to compare on price. Weak search visibility keeps you out of the comparison entirely. We solve both sides of that problem.',
    question:'What is the point of looking credible if the right people never find you?',
    answer:'Branding earns recognition and search earns discovery. For a service business, they should tell the same story: what you specialise in, where you work, what makes the experience different, and why a buyer should trust you with the job.',
    chapters:[['Positioning before decoration','We clarify the audience, category, offer, differentiators, and personality before choosing colours or type. The result is a brand direction rooted in the way you want to be understood.'],['Search built around real intent','We research how buyers describe the problem, compare providers, and search by service or location. That evidence shapes page priorities, headings, metadata, and content briefs.'],['Local trust across the web','Your website, Google Business Profile, directories, service areas, and contact details should reinforce one another. We find inconsistencies and strengthen the signals that help local buyers verify the business.'],['Content that deserves to rank','Useful service pages and answer-led articles cover a subject with enough clarity to help a real person. We optimise structure and relevance without awkward keyword repetition.']],
    steps:[['Audit the signals','Review positioning, identity, competitors, search visibility, and local profiles.'],['Choose the ground','Prioritise audiences, services, locations, search themes, and brand direction.'],['Apply consistently','Build the identity system and improve pages, metadata, profiles, and content.'],['Measure and deepen','Review visibility and enquiries, then expand the areas showing commercial relevance.']],
    faqs:[['Do branding and SEO need to be purchased together?','No. They can be scoped separately. We combine them here because recognition and discovery often fail at the same handoff, but your actual bottleneck determines the work.'],['Can you guarantee first-page rankings?','No credible SEO provider can guarantee a position controlled by a search engine. We can improve technical foundations, relevance, local consistency, content quality, and measurement, then report what is and is not moving.'],['What is local SEO?','Local SEO improves how clearly a business communicates its services, location, and credibility across its website, Google Business Profile, and relevant listings.'],['Can you work with our existing logo?','Yes. If the logo is usable, we can strengthen the surrounding system: typography, colour, imagery, voice, layouts, and guidelines.']],
    related:['web-development','content-writing']
  },
  'digital-marketing': {
    headline:['Buying clicks is easy.','Making them pay is the work.'],
    lead:'More traffic does not repair a weak offer or confusing landing page. We connect the entire paid journey so every campaign has a fair chance to produce qualified demand.',
    question:'Why do paid campaigns spend money without producing enough good leads?',
    answer:'Often the ad, offer, landing page, and follow-up were built as separate tasks. The audience sees one promise, lands on a generic page, meets friction in the form, then receives a slow response. We treat that as one system and optimise the handoffs.',
    chapters:[['An offer worth interrupting someone for','We define the audience, pain point, promise, evidence, and action before choosing channels. The campaign needs a commercially useful reason to exist.'],['Creative matched to intent','A search ad meets active demand differently from a social ad creating attention. Messaging and creative are shaped around the intent present in each channel.'],['A landing page that continues the promise','The destination mirrors the ad, answers the next objections, provides proof, and makes the action easy on mobile.'],['Measurement that informs a decision','Clicks and impressions are context, not the finish line. Where tracking permits, we focus on calls, forms, bookings, lead quality, and downstream sales signals.']],
    steps:[['Define the economics','Clarify the offer, audience, budget, lead value, capacity, and useful conversion events.'],['Build the journey','Create channel-specific ads, landing pages, forms, tracking, and follow-up requirements.'],['Launch with control','Monitor spend, search terms, delivery, and conversion signals.'],['Improve the constraint','Refine targeting, creative, offer, landing page, or follow-up using evidence.']],
    faqs:[['Is advertising spend included?','No. Media spend and third-party platform costs are separate unless a proposal explicitly says otherwise.'],['Should I use Google Ads or social ads?','Google Ads often captures existing demand; paid social can create or recapture attention. The right choice depends on the offer, audience, sales cycle, location, creative, and budget.'],['How do you measure lead quality?','Tracking can record forms, calls, and bookings, but the business must help identify which leads became real opportunities.'],['Can you fix an existing campaign?','Yes. We can audit account structure, targeting, ads, landing pages, tracking, and follow-up before recommending optimisation or a rebuild.']],
    related:['web-development','email-marketing']
  },
  'email-marketing': {
    headline:['The lead went quiet.','You do not have to.'],
    lead:'People get busy, compare options, and postpone decisions. Timely, useful follow-up keeps the conversation alive without turning your brand into inbox noise.',
    question:'How many potential clients are lost simply because nobody followed up well?',
    answer:'The first enquiry rarely contains every answer a buyer needs. A thoughtful sequence can confirm what happens next, address common concerns, provide proof, and invite a decision when the person is ready. The goal is not more email. It is fewer good opportunities forgotten.',
    chapters:[['Map the moments that matter','We identify what should happen after an enquiry, quote, download, appointment, purchase, or period of silence.'],['Write like a helpful business','Clear subject lines, human copy, useful details, and one primary action make messages easier to trust.'],['Automate without becoming robotic','Welcome, nurture, reminder, and re-engagement journeys handle predictable follow-up while leaving room for personal conversations.'],['Learn from behaviour','Deliverability, opens, clicks, replies, bookings, and conversions provide different clues. We interpret them in context.']],
    steps:[['Find the drop-off','Review the audience, permission, platform, sales process, and missed follow-up moments.'],['Map the sequence','Define triggers, segments, objections, messages, timing, and human handoffs.'],['Create and connect','Write, design, configure, and test the emails and automation.'],['Review what happened','Refine weak messages and journeys using engagement and business feedback.']],
    faqs:[['What email automations can you build?','Typical journeys include enquiry acknowledgement, nurture, quote follow-up, reminders, onboarding, review requests, and re-engagement.'],['Can you work with our current platform?','Usually, yes. We review its automation, segmentation, integration, and reporting capabilities first.'],['Do you provide email lists?','No. We work with permission-based contacts and legitimate list-growth methods.'],['Will you write and design the emails?','Yes. Scope can include strategy, copy, responsive design, platform setup, automation, testing, and reporting.']],
    related:['digital-marketing','content-writing']
  },
  'content-writing': {
    headline:['Your expertise is valuable.','If buyers understand it.'],
    lead:'“Quality service” and “customer-focused solutions” say almost nothing. We find the substance inside your business and turn it into credible reasons to choose you.',
    question:'Why does so much business copy sound polished but fail to persuade?',
    answer:'Because it describes the company instead of helping the buyer decide. Strong copy names the real problem, makes a specific promise, explains the approach, supports it with proof, answers objections, and asks for a sensible next step.',
    chapters:[['Interview the expertise out of you','We ask about customers, objections, process, trade-offs, proof, competitors, and the details your team explains on real sales calls.'],['Give every page one job','A homepage orients. A service page helps someone evaluate. A case study demonstrates thinking. An article answers a question.'],['Optimise for humans and search systems','Clear headings, descriptive titles, direct answers, natural terminology, internal links, and complete explanations help readers and search systems understand the page.'],['Turn reputation into usable proof','Reviews reveal what people value, doubt, and remember. We use those patterns to strengthen messaging and guide consistent responses.']],
    steps:[['Extract the truth','Gather interviews, reviews, sales questions, examples, offers, and existing material.'],['Find the argument','Define the purpose, audience, pain, promise, proof, objections, and action.'],['Write and challenge','Draft for persuasion, then fact-check specifics with the people closest to the work.'],['Publish with structure','Apply headings, metadata, links, relevant schema, and a consistent voice.']],
    faqs:[['What is conversion copywriting?','It helps a specific reader make a decision by connecting a real pain to a relevant outcome, evidence, objections, and a clear next step.'],['How do you make copy SEO and AEO friendly?','We research intent, answer the core question directly, use descriptive headings, cover the subject thoroughly, connect related pages, and add valid structured data where relevant.'],['Will the copy sound like our business?','Yes. Interviews, sales language, reviews, and factual review provide the raw material; brand-voice guidance keeps it consistent.'],['Can you guarantee higher conversions?','No one can honestly guarantee a result without controlling traffic, offer, pricing, reputation, competition, and follow-up. We make the journey clearer and measurable, then improve it using evidence.']],
    related:['web-development','branding-seo']
  },
  waas: {
    headline:['Your website is live.','Now keep it useful.'],
    lead:'A launch is one day. The business keeps changing after it. Website as a Service gives the site an accountable team, a defined monthly scope, and a route for the next improvement.',
    question:'What is Website as a Service, and who is it for?',
    answer:'Website as a Service combines an initial website with agreed maintenance, updates, and digital support for a monthly fee. It suits businesses that want a professionally managed website without coordinating separate designers, developers, hosting support, SEO providers, and update requests.',
    chapters:[['Begin with a business case','We define the audience, services, pages, content, features, and commercial role before confirming the plan and initial build.'],['One home for routine website work','Maintenance, security, monitoring, and agreed content changes have a clear owner and request process.'],['Keep the offer accurate','Services, team details, proof, locations, promotions, and customer questions change. Monthly capacity gives important updates a regular path onto the site.'],['Improve beyond maintenance','Depending on the plan, SEO, local presence, content, reputation, CRM, and email work can extend the site into a broader growth system.']],
    steps:[['Choose the outcome','Discuss the business, bottleneck, pages, and level of ongoing support.'],['Confirm the boundaries','Document deliverables, requests, third-party costs, ownership, and terms.'],['Build and launch','Complete strategy, design, development, integrations, testing, and launch.'],['Run the next month','Maintain the site, complete prioritised work, and agree what matters next.']],
    faqs:[['How is WaaS different from a one-time project?','A one-time project ends with delivery. Website as a Service continues with a defined monthly scope for maintenance, updates, and included growth services.'],['Are website changes unlimited?','No. Each proposal defines included work, prioritisation, response expectations, and how out-of-scope work is quoted.'],['How much does Website as a Service cost?','Current plans start at $999.99 per month. Higher plans add technical SEO, local profile optimisation, local SEO, guest posting, and ongoing articles.'],['Who owns the website?','Ownership, hosting, access, cancellation, and handover terms are set out in the written agreement for your plan.']],
    related:['web-development','branding-seo']
  }
};
